openai_api_key: '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'

tmdb_access_token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZGJhYjU5MGM3ZWFjYTA3ZWJlNjI1OTc0YTM3YWQ5MiIsInN1YiI6IjY1MmNmODM3NjYxMWI0MDBmZmM3MDM5OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.McsK4Wm5XnRSDLn62Jhy787YUAwZcQz0X5qzkGuLe_s

spotipy_client_id: "43e3f643c51949cfa0c8f4afc32f19dc"
spotipy_client_secret: "3b3bda7053c04b009ba1ec075999c6b1"
spotipy_redirect_uri: "https://shizhl.top"